name: IM939
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=5.4.*
  - geopandas=1.0.*
  - pandas=2.2.*
  - pip
  - python=3.12.4
  - jupyterlab
  - openpyxl
  - scikit-learn
  - seaborn=0.13.*
  - pip:
    - ghp-import
    - jupyterlab-quarto
 